SET(TEST_SRCS ./algorithm/copy_backward_test.cpp
              ./algorithm/copy_test.cpp
              ./algorithm/equal_test.cpp
              ./algorithm/fill_n_test.cpp
              ./algorithm/fill_test.cpp
              ./algorithm/iter_swap_test.cpp
              ./algorithm/lexicographical_compare_test.cpp
              ./algorithm/max_test.cpp
              ./algorithm/min_test.cpp
              ./algorithm/move_test.cpp
              ./algorithm/reverse_test.cpp
              ./algorithm/rotate_test.cpp
              ./allocator/allocator_test.cpp
              ./allocator/allocator_traits_test.cpp
              ./any/any_test.cpp
              ./container/function/at_test.cpp
              ./container/function/back_test.cpp
              ./container/function/clear_test.cpp
              ./container/function/data_test.cpp
              ./container/function/front_test.cpp
              ./container/function/is_emtpy_test.cpp
              ./container/function/push_back_test.cpp
              ./container/function/size_test.cpp
              ./container/vector_test.cpp
              ./iterator/advance_test.cpp
              ./iterator/distance_test.cpp
              ./iterator/iterator_test.cpp
              ./iterator/iterator_traits_test.cpp
              ./iterator/move_iterator_test.cpp
              ./iterator/normal_iterator_test.cpp
              ./iterator/range_test.cpp
              ./iterator/reverse_iterator_test.cpp
              ./main.cpp
              ./math/gcd_test.cpp
              ./mpl/and_test.cpp
              ./mpl/bool_test.cpp
              ./mpl/eval_if_test.cpp
              ./mpl/if_test.cpp
              ./mpl/integral_c_test.cpp
              ./mpl/not_test.cpp
              ./mpl/or_test.cpp
              ./type_traits/add_const_test.cpp
              ./type_traits/add_cv_test.cpp
              ./type_traits/add_lvalue_reference_test.cpp
              ./type_traits/add_rvalue_reference_test.cpp
              ./type_traits/add_volatile_test.cpp
              ./type_traits/enable_if_test.cpp
              ./type_traits/has_difference_type_test.cpp
              ./type_traits/has_element_type.cpp
              ./type_traits/has_iterator_test.cpp
              ./type_traits/has_pointer_test.cpp
              ./type_traits/has_type_test.cpp
              ./type_traits/has_value_type_test.cpp
              ./type_traits/is_array_test.cpp
              ./type_traits/is_base_of_test.cpp
              ./type_traits/is_byte_test.cpp
              ./type_traits/is_class_test.cpp
              ./type_traits/is_constructible_test.cpp
              ./type_traits/is_const_test.cpp
              ./type_traits/is_default_constructible_test.cpp
              ./type_traits/is_enum_test.cpp
              ./type_traits/is_floating_point_test.cpp
              ./type_traits/is_integral_test.cpp
              ./type_traits/is_lvalue_reference_test.cpp
              ./type_traits/is_pointer_test.cpp
              ./type_traits/is_reference_test.cpp
              ./type_traits/is_rvalue_reference_test.cpp
              ./type_traits/is_same_test.cpp
              ./type_traits/is_signed_test.cpp
              ./type_traits/is_trival_test.cpp
              ./type_traits/is_trivially_destructible_test.cpp
              ./type_traits/is_union_test.cpp
              ./type_traits/is_void_test.cpp
              ./type_traits/is_volatile_test.cpp
              ./type_traits/make_unsigned/enum.cpp
              ./type_traits/make_unsigned/signed.cpp
              ./type_traits/make_unsigned/unsigned.cpp
              ./type_traits/propagate_cv_test.cpp
              ./type_traits/remove_all_extends.cpp
              ./type_traits/remove_const_test.cpp
              ./type_traits/remove_cv_test.cpp
              ./type_traits/remove_extends_test.cpp
              ./type_traits/remove_reference_test.cpp
              ./type_traits/remove_volatile_test.cpp
              ./uninitialized/uninitialized_copy_test.cpp
              ./uninitialized/uninitialized_default_test.cpp
              ./uninitialized/uninitialized_fill_test.cpp
              ./uninitialized/uninitialized_move_test.cpp
              ./utility/addressof_test.cpp
              ./utility/forward_test.cpp
              ./utility/move_if_noexcept_test.cpp
              ./utility/move_test.cpp
              ./utility/noncopyable_test.cpp
              ./utility/pointer_traits_test.cpp
              ./utility/swap_test.cpp
              )
